version: '3'

networks:
  laravel:

services:

  weather-nginx:
    image: nginx:stable-alpine
    container_name: weather-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx/init.sh:/usr/local/bin/nginx-init.sh
    depends_on:
      - weather-php
      - weather-mysql
    networks:
      - laravel

  weather-mysql:
    image: mariadb:latest
    container_name: weather-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  weather-php:
    build:
      args:
        - USER_ID=1000
        - GROUP_ID=1000
      context: . 
      dockerfile: Dockerfile
    container_name: weather-php
    restart: unless-stopped
    tty: true
    environment: 
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
     - "9000:9000"
    networks:
      - laravel

